[package]
name = "rusty_sand"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.11.2", features = ["multi-threaded", "dynamic_linking"]}
bevy_egui = "0.21.0"
image = "0.24.7"
wgpu = "0.17.0"
winit = "0.28.6"

[toolchain]
channel = "nightly"
