[package]
name = "rusty_sand"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.11.1"}
image = "0.24.7"
winit = "0.28.6"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-Zshare-generics=off"]

[toolchain]
channel = "nightly"